export const gigData = [
  {
    title: 'I will develop a full-stack web application for your business by @BOASE',
    description: 'Leverage my expertise in Next.js, React, Node.js, and Supabase to build a robust and scalable web application tailored to your specific needs. From UI/UX design to database management and deployment, I offer comprehensive development services by @BOASE.',
    category: 'Development',
    sub_category: 'Web Application',
    skills_required: 'Next.js, React, Node.js, Supabase, TypeScript, TailwindCSS',
    budget_type: 'negotiable' as const,
    budget_amount_min: '1000',
    budget_amount_max: '5000',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'full-stack, web development, Next.js, React, Supabase, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will design and implement a modern UI/UX for your website by @BOASE',
    description: 'Enhance user engagement with a visually appealing and intuitive UI/UX design. I specialize in creating user-centered designs using Figma and implementing them with modern front-end technologies like React and TailwindCSS, by @BOASE.',
    category: 'Design',
    sub_category: 'UI/UX Design',
    skills_required: 'Figma, React, TailwindCSS, UI Design, UX Design',
    budget_type: 'fixed' as const,
    budget_amount_min: '500',
    budget_amount_max: '2000',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'UI design, UX design, web design, Figma, React, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will integrate Supabase backend services into your application by @BOASE',
    description: 'Seamlessly integrate Supabase for authentication, database management, storage, and real-time functionalities. I will ensure your application is scalable and secure with Supabase, by @BOASE.',
    category: 'Development',
    sub_category: 'Backend Integration',
    skills_required: 'Supabase, PostgreSQL, Authentication, Real-time, Storage',
    budget_type: 'hourly' as const,
    budget_amount_min: '50',
    budget_amount_max: '100',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'Supabase, backend, database, authentication, real-time, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will build a custom admin dashboard for your application by @BOASE',
    description: "Get a custom-built admin dashboard to manage your application's data, users, and settings efficiently. I will use React and your preferred UI library to create a powerful and user-friendly admin panel, by @BOASE.",
    category: 'Development',
    sub_category: 'Admin Panel',
    skills_required: 'React, Next.js, Supabase, Data Visualization, API Integration',
    budget_type: 'fixed' as const,
    budget_amount_min: '800',
    budget_amount_max: '2500',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'admin dashboard, admin panel, React, data management, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will develop secure authentication and user management features by @BOASE',
    description: 'Implement robust authentication (including social logins) and user profile management for your application using Supabase Auth or other identity solutions, by @BOASE.',
    category: 'Development',
    sub_category: 'Authentication',
    skills_required: 'Supabase Auth, OAuth, User Management, Security, Next.js',
    budget_type: 'fixed' as const,
    budget_amount_min: '300',
    budget_amount_max: '1000',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'authentication, user management, security, Supabase, OAuth, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will create and manage your Supabase database schema by @BOASE',
    description: 'Design, implement, and manage your PostgreSQL database schema on Supabase, including tables, relationships, and RLS policies for data security, by @BOASE.',
    category: 'Development',
    sub_category: 'Database Management',
    skills_required: 'Supabase, PostgreSQL, SQL, Database Design, RLS',
    budget_type: 'hourly' as const,
    budget_amount_min: '40',
    budget_amount_max: '80',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'database, Supabase, PostgreSQL, schema design, RLS, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will build API endpoints for your application using Next.js and Supabase by @BOASE',
    description: 'Develop secure and efficient RESTful or GraphQL API endpoints using Next.js API routes and Supabase for data interaction, by @BOASE.',
    category: 'Development',
    sub_category: 'API Development',
    skills_required: 'Next.js, Supabase, REST API, GraphQL, Node.js',
    budget_type: 'negotiable' as const,
    budget_amount_min: '400',
    budget_amount_max: '1500',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'API development, Next.js, Supabase, backend, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will implement real-time features using Supabase Realtime by @BOASE',
    description: 'Add real-time capabilities to your application, such as live chat, notifications, or collaborative editing, powered by Supabase Realtime, by @BOASE.',
    category: 'Development',
    sub_category: 'Real-time Features',
    skills_required: 'Supabase Realtime, WebSockets, JavaScript, React',
    budget_type: 'fixed' as const,
    budget_amount_min: '350',
    budget_amount_max: '1200',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'real-time, Supabase, notifications, chat, collaborative editing, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will set up Supabase Storage for file uploads and management by @BOASE',
    description: 'Integrate Supabase Storage into your application for secure and efficient file uploads, downloads, and management, including image optimization, by @BOASE.',
    category: 'Development',
    sub_category: 'File Storage',
    skills_required: 'Supabase Storage, File Management, Image Optimization, Next.js',
    budget_type: 'fixed' as const,
    budget_amount_min: '250',
    budget_amount_max: '800',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'file storage, Supabase, uploads, image management, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will deploy your Next.js application to Vercel or Netlify by @BOASE',
    description: 'Professionally deploy your Next.js application to Vercel, Netlify, or your preferred hosting platform, including CI/CD setup, by @BOASE.',
    category: 'Development',
    sub_category: 'Deployment',
    skills_required: 'Vercel, Netlify, CI/CD, Next.js, Git',
    budget_type: 'fixed' as const,
    budget_amount_min: '150',
    budget_amount_max: '500',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'deployment, Vercel, Netlify, CI/CD, Next.js, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will develop custom Supabase Edge Functions for your backend logic by @BOASE',
    description: 'Write, test, and deploy custom Deno-based Supabase Edge Functions to handle server-side logic, webhooks, or cron jobs efficiently, by @BOASE.',
    category: 'Development',
    sub_category: 'Edge Functions',
    skills_required: 'Supabase Edge Functions, Deno, TypeScript, Serverless',
    budget_type: 'hourly' as const,
    budget_amount_min: '60',
    budget_amount_max: '120',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'Supabase, edge functions, serverless, Deno, backend, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will optimize your Next.js application for performance and SEO by @BOASE',
    description: "Improve your Next.js application's loading speed, performance metrics (LCP, FID, CLS), and SEO ranking through code optimization, image optimization, and server-side rendering strategies, by @BOASE.",
    category: 'Development',
    sub_category: 'Optimization',
    skills_required: 'Next.js, Performance Optimization, SEO, Lighthouse, Web Vitals',
    budget_type: 'negotiable' as const,
    budget_amount_min: '400',
    budget_amount_max: '1500',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'performance, SEO, Next.js, optimization, web vitals, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will provide ongoing maintenance and support for your Supabase project by @BOASE',
    description: 'Offer reliable maintenance and support services for your Supabase and Next.js application, including bug fixes, updates, and monitoring, by @BOASE.',
    category: 'Support',
    sub_category: 'Maintenance',
    skills_required: 'Supabase, Next.js, Troubleshooting, Debugging, Monitoring',
    budget_type: 'hourly' as const,
    budget_amount_min: '50',
    budget_amount_max: '90',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'maintenance, support, Supabase, Next.js, bug fixing, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will build a component library for your project using Storybook by @BOASE',
    description: 'Create a reusable and well-documented component library for your React/Next.js project using Storybook to ensure consistency and accelerate development, by @BOASE.',
    category: 'Development',
    sub_category: 'Component Library',
    skills_required: 'React, Next.js, Storybook, Component Design, TypeScript',
    budget_type: 'fixed' as const,
    budget_amount_min: '700',
    budget_amount_max: '2200',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'component library, Storybook, React, UI development, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will integrate third-party APIs into your application by @BOASE',
    description: 'Seamlessly integrate various third-party APIs (e.g., payment gateways, social media, analytics) into your Next.js and Supabase application, by @BOASE.',
    category: 'Development',
    sub_category: 'API Integration',
    skills_required: 'API Integration, Next.js, Supabase, Node.js, REST, GraphQL',
    budget_type: 'negotiable' as const,
    budget_amount_min: '300',
    budget_amount_max: '1200',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'API integration, third-party API, backend, Next.js, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will set up a project management or team collaboration tool by @BOASE',
    description: "Help you set up and configure project management tools like Jira, Trello, or Asana, or team collaboration platforms to streamline your workflow, by @BOASE. Based on the 'team' and 'projects' sections of b0ase.",
    category: 'Consulting',
    sub_category: 'Project Management',
    skills_required: 'Project Management Tools, Team Collaboration, Workflow Optimization',
    budget_type: 'fixed' as const,
    budget_amount_min: '200',
    budget_amount_max: '600',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'project management, team collaboration, Jira, Trello, Asana, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will help manage your finances and invoicing within b0ase by @BOASE',
    description: "Assist with setting up and utilizing the finance tracking and invoicing features within the b0ase platform, by @BOASE. Based on the 'finances' section.",
    category: 'Consulting',
    sub_category: 'Financial Management',
    skills_required: 'Financial Tracking, Invoicing, b0ase Platform Knowledge',
    budget_type: 'hourly' as const,
    budget_amount_min: '30',
    budget_amount_max: '70',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'finances, invoicing, b0ase, financial consulting, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will create a content strategy and populate your b0ase diary/blog by @BOASE',
    description: "Develop a content strategy for your b0ase diary or blog section and help create engaging posts to document progress or share insights, by @BOASE. Based on the 'diary' section.",
    category: 'Content',
    sub_category: 'Content Creation',
    skills_required: 'Content Strategy, Writing, SEO, b0ase Platform Knowledge',
    budget_type: 'negotiable' as const,
    budget_amount_min: '250',
    budget_amount_max: '900',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'content creation, blogging, content strategy, diary, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will manage your tokenomics and B0ASE token aspects by @BOASE',
    description: "Provide consultation and management services for your B0ASE token, including aspects visible in 'mytoken' and 'boasetoken' sections, by @BOASE.",
    category: 'Blockchain',
    sub_category: 'Token Management',
    skills_required: 'Tokenomics, Cryptocurrency, Blockchain, Supabase Integration',
    budget_type: 'hourly' as const,
    budget_amount_min: '70',
    budget_amount_max: '150',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'tokenomics, B0ASE token, cryptocurrency, blockchain, @BOASE',
    deadline: '',
    is_published: true,
  },
  {
    title: 'I will assist in scraping and utilizing Fiverr data for market research by @BOASE',
    description: "Leverage the 'fiverrscraper' functionality to gather insights from Fiverr for competitive analysis and market research for your services, by @BOASE.",
    category: 'Marketing',
    sub_category: 'Market Research',
    skills_required: 'Web Scraping, Data Analysis, Market Research, Fiverr Platform',
    budget_type: 'fixed' as const,
    budget_amount_min: '300',
    budget_amount_max: '1000',
    currency: 'USD',
    location_preference: 'remote' as const,
    tags: 'market research, fiverr scraper, data analysis, competitive analysis, @BOASE',
    deadline: '',
    is_published: true,
  }
]; 